apiVersion: v1
kind: ConfigMap
metadata:
  name: kip-auth-config
  namespace: kip-poc
  labels:
    app: kip-auth
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "5001"
  NACOS_SERVER_ADDR: "__NACOS_SERVER_ADDR__"
  NACOS_NAMESPACE: "__NACOS_NAMESPACE__"
  NACOS_GROUP: "__NACOS_GROUP__"
  NACOS_CONFIG_ENABLED: "true"
  NACOS_DISCOVERY_ENABLED: "false"
  NACOS_REGISTER_ENABLED: "false"
  NACOS_AUTO_REGISTRATION_ENABLED: "false"
  REDIS_HOST: "kip-redis"
  REDIS_PORT: "6379"
