apiVersion: v1
kind: Service
metadata:
  name: kip-auth
  namespace: kip-poc
  labels:
    app: kip-auth
spec:
  selector:
    app: kip-auth
  ports:
    - name: http
      port: 5001
      targetPort: http
