spring:
  profiles:
    active: dev
  application:
    name: kip-auth
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml

  cloud:
    nacos:
      discovery:
        server-addr: 10.42.0.125:8848
        register-enabled: true
        group: DEFAULT_GROUP
        namespace: ""
      config:
        server-addr: 10.42.0.125:8848
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: ""
        refresh-enabled: true
    sentinel:
      transport:
        port: 8090
      web-context-unify: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.kip.auth.dal.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
