spring:
  profiles:
    active: dev
  application:
    name: kip-auth
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yml  # 可选的 Nacos 配置导入

  cloud:
    nacos:
      # 服务注册与发现配置
      discovery:
        server-addr: 10.42.0.125:8848
        register-enabled: true
        group: DEFAULT_GROUP
        namespace: ""

      config:
        server-addr: 10.42.0.125:8848
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: ""
        refresh-enabled: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.kip.auth.dal.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  cloud:
    sentinel:
      transport:
        port: 8090
      web-context-unify: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
